name: Generate Pac-Man

on:
  schedule:
    - cron: "0 0 * * *" # roda todo dia à meia-noite (UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Pac-Man SVG
        uses: Platane/snk@v3
        with:
          github_user_name: victormoni
          mode: pacman
          outputs: |
            dist/pacman.svg?palette=github-light&color_snake=%23FFCC00
            dist/pacman-dark.svg?palette=github-dark&color_snake=%23FFCC00

      - name: Publish to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
